//Assignment 3 - Rando Video for CART 353
//Written by Matthew Salaciak 29644490
//This is the gaussian class I created to implement the gaussian distribution on values taken from the pixel array of my webcam

// uses processings random library to use the nextGaussian function
import java.util.Random;
class Gaussian {
  
  //variable declaration
  Random generator = new Random();
  float gaus = 0;
  float randomFactor = 0;
  float std =50;
  boolean change = true;
  
  //constructor
  // random factor is explained in the freakOut method, but this is the what i pass the variable loc,loc2,loc3 to.
 Gaussian(float x) {
   
   this.randomFactor =  x;

}

//this method takes random number generated by the nextGaussian function, multiplies it by a standard deviation
//and adds the randomFactor varible to it.
//before returning the variable, it is in a while loop that goes through a series of if statements which each have their own unique
//changes to the gaussian value
//the if statements are controlled by a variable called the controlFactor that increases with each iteration 
//when it reaches the last if statement the boolean variable change is set to false, to leave the while loop
//i wanted to do this in order to furthur the randomness and create a more distorted effect.


float freakOut () {
   
 int controlFactor = 0;
  while(change) {
  if(controlFactor < 3){
    gaus= (float)generator.nextGaussian();
    gaus*=std+10;
     gaus+=randomFactor*200;
    } 
    if(controlFactor<5) {
   gaus= (float)generator.nextGaussian();
    gaus*=std+50;
    gaus+=randomFactor/400;
    
    
    
  } if(controlFactor<9){
     gaus= (float)generator.nextGaussian();
     gaus*=std-75;
   gaus+=randomFactor*80;
    change = false;
    
  }
  controlFactor++;
  
  
  }
  
  return gaus;
}
  
  
  
}